EDUCATIONAL_KEYWORDS = {
    "science": [
    # **Basic Topics**
    "Anatomy", "Ecology", "Photosynthesis", "Respiration in plants", "Cell division", "Atomic structure", 
    "Chemical reactions", "Periodic table", "States of matter", "Genetic engineering", "Nanotechnology",
    "Quantum mechanics", "Thermodynamics", "Greenhouse effect", "Environmental conservation", "Space exploration", 
    "Bioinformatics", "Bioethics", "Human biology", "Plant biology", "Fossils", "Forensic science", "Particle accelerators",

    # **Intermediate Topics**
    "Cell biology", "Molecular biology", "Biotechnology", "Photosynthesis process", "Genetics", "Evolution", 
    "Thermodynamics laws", "Climate change", "Environmental science", "Atmospheric science", "Astrobiology", 
    "Hydrology", "Microbiology", "Marine biology", "Botany", "Zoology", "Mycology", "Entomology", "Virology", 
    "Astrophysics", "Geology", "Biochemistry", "Organic chemistry", "Inorganic chemistry", "Physical chemistry", 
    "Electromagnetism", "Mechanics", "Nuclear physics", "Fluid dynamics", "Acoustics", "Optics", "Radioactivity", 
    "Chemical engineering", "Geochemistry", "Solid-state physics", "Materials science", "Neuroscience", 
    "Cognitive science", "Biomedical engineering", "Artificial photosynthesis", "Green chemistry", "Waste management", 
    "Sustainable energy", "Energy conversion", "Climate modeling", "Carbon footprint", "Seismology", "Volcanology",

    # **Advanced Topics**
    "Quantum field theory", "String theory", "Quantum computing", "Advanced genetic engineering", "CRISPR technology", 
    "Nanomedicine", "Synthetic biology", "Stem cell research", "Astrophysics and cosmology", "Dark matter", 
    "Dark energy", "Exoplanets", "Neurobiology", "Neural networks in biology", "High-energy physics", 
    "Relativity theory", "Gravitational waves", "Space-time", "Advanced thermodynamics", "Quantum chemistry", 
    "Molecular dynamics simulations", "Nonlinear dynamics", "Chaos theory", "Advanced nuclear fusion", 
    "Superconductivity", "Artificial intelligence in science", "Deep learning in biology", "Machine learning in chemistry", 
    "Robotics in space exploration", "Bioinorganic chemistry", "Advanced environmental chemistry", "Metallurgy", 
    "Paleoclimatology", "Geoengineering", "Global warming", "Epigenetics", "Pharmacogenomics", "Bioinformatics algorithms", 
    "Medical imaging technologies", "Advanced computational biology", "Biomaterials", "Biomechanics", "Astrobiology research", 
    "Neuroengineering", "Quantum optics", "Laser spectroscopy", "Computational chemistry", "Molecular spectroscopy", 
    "Artificial intelligence in physics", "Cryogenics", "Magnetohydrodynamics", "Biocatalysis", "Neutron scattering", 
    "Synthetic polymers", "Advanced nanotechnology", "Molecular electronics", "Graphene technology"
    ],

    "mathematics": [
    # **Basic Topics**
    "Arithmetic operations", "Fractions", "Decimals", "Basic algebraic equations", "Probability", 
    "Coordinate geometry", "Prime numbers", "Mean", "Median", "Mode", "Linear equations", "Polynomials", 
    "Basic geometry", "Number systems", "Ratios and proportions", "Percentages", "Time and work", "Time and distance", 
    "Mensuration", "Statistics", "Combinations and permutations", "Quadratic equations", "Logarithms", "Algebraic expressions",
    "Matrices", "Vectors", "Introduction to calculus", "Basic graph theory", "Simplification of algebraic expressions", 
    "Geometric progressions", "Arithmetic progressions", "Number theory", "Trigonometric identities", 
    "Linear algebra basics", "Complex numbers basics", "Exponents and powers", "Mathematical induction", "Differentiation basics", 
    "Integration basics", "Probability theory", "Set theory basics", "Logic gates", "Polynomials division", 
    "Coordinate transformations", "Basic trigonometry", "Functions and their graphs", "Basic statistical concepts", 
    "Simple interest", "Compound interest", "Linear programming basics", "Binomial expansions", "Simultaneous equations", 
    "Exponential functions", "Rational expressions", "Basic inequalities", "Synthetic division", "Modular arithmetic", 
    "Cubic equations", "Logarithmic functions", "Matrix operations", "Determinants", "Linear relations", 
    "Basic combinatorics", "Prime factorization", "Pythagoras theorem", "Basic derivatives", "Basic integrals", 
    "Laws of indices", "Basic trigonometric functions", "Surface area and volume", "Linear inequalities", "Basic probability distributions",

    # **Intermediate Topics**
    "Set theory", "Linear algebra", "Graph theory", "Differentiation", "Integration", "Matrices", "Eigenvalues", "Eigenvectors",
    "Vector spaces", "Trigonometric functions", "Sequence and series", "Modular arithmetic", "Bayesian statistics", 
    "Probability distributions", "Markov chains", "Mathematical induction", "Operations research", "Differential equations",
    "Boolean algebra", "Logic gates", "Operations with matrices", "Fourier transforms", "Laplace transforms", 
    "Fractals", "Homogeneous equations", "Partial fractions", "Parametric equations", "Riemann sums", "PDEs (Partial Differential Equations)", 
    "ODEs (Ordinary Differential Equations)", "Solving systems of equations", "Abstract algebra", "Mathematical modeling", 
    "Optimization techniques", "Vector calculus", "Numerical methods", "Probability theory", "Stochastic processes", 
    "Decision theory", "Probability theory and distributions", "Game theory", "Cryptography", "Graph algorithms", 
    "Mathematical logic", "Nonlinear programming", "Stochastic differential equations", "Computational geometry", 
    "Mathematical finance", "Bayesian networks", "Statistical inference", "Statistical mechanics", "Mathematical physics", 
    "P-adic numbers", "Finite geometry", "Algorithms", "Numerical analysis", "Real analysis", "Functional analysis", 
    "Differential topology", "Elliptic curves", "Functional equations", "Linear optimization", "Queueing theory", "Graph coloring", 
    "Operations with complex numbers", "Recurrence relations", "Complex analysis", "Statistical mechanics",

    # **Advanced Topics**
    "Multivariable calculus", "Abstract algebra", "Topology", "Differential equations", "Combinatorics", "Group theory", 
    "Ring theory", "Field theory", "Homotopy", "Homology", "Galois theory", "Mathematical logic", "Category theory", 
    "Set theory", "Measure theory", "Advanced calculus", "Complex analysis", "Differential forms", "Quantum mechanics mathematics", 
    "Fractal geometry", "Riemannian geometry", "Mathematical induction", "Computational mathematics", "Functional analysis", 
    "Homomorphic encryption", "Elliptic curves", "Advanced number theory", "Geometric topology", "Advanced optimization", 
    "Mathematical modeling in biology", "Topological spaces", "Advanced cryptography", "Mathematical finance", 
    "Stochastic processes", "Infinite series", "PDE (Partial Differential Equations)", "Tensor analysis", "Calculus of variations", 
    "Game theory in economics", "Advanced game theory", "Quantum computing mathematics", "Advanced combinatorics", 
    "Optimization theory", "Algorithmic complexity", "Multivariate statistics", "Principal component analysis", 
    "Machine learning algorithms", "Neural networks", "Support vector machines", "Data mining", "Big data analytics", 
    "Dimensionality reduction", "Reinforcement learning", "Deep learning", "Clustering algorithms", "Fuzzy logic", 
    "Multi-objective optimization", "Quantum field theory", "Advanced Fourier analysis", "Simulation theory", 
    "Mathematical foundations of machine learning", "Tensor networks", "Information theory", "Hyperbolic geometry", 
    "K-theory", "Non-Euclidean geometry", "Topological data analysis", "Advanced statistical mechanics", 
    "Topology of manifolds", "Advanced optimization techniques", "Advanced cryptography algorithms", "Elliptic curve cryptography", 
    "Simulation theory", "Quantum mechanics mathematics", "Mathematical models in physics", "Computational algebraic geometry", 
    "Inverse problems", "Theory of automata", "Topology of dynamical systems", "Operator theory", "Game theory in AI",
    "Advanced probability theory", "Markov decision processes"
    ],

    "chemistry": [
    "Chemical bonding", "Atomic structure", "Periodic trends", "Chemical reactions", "Acids and bases", 
    "Solutions", "Atomic theory", "Redox reactions", "Organic synthesis", "Electrochemistry", "Thermodynamics", 
    "Polymer chemistry", "Supramolecular chemistry", "Computational chemistry", "Bioinformatics", "Chemical equilibrium", 
    "Analytical techniques", "Industrial chemistry", "Environmental chemistry", "Chemical safety", 
    "Acids", "Bases", "pH scale", "Buffer solutions", "Strong acids", "Weak acids", "Strong bases", "Weak bases", 
    "Arrhenius acid-base theory", "Bronsted-Lowry acid-base theory", "Lewis acid-base theory", 
    "Conjugate acids and bases", "Acid rain", "Acid dissociation constant (Ka)", "Base dissociation constant (Kb)", 
    "Titration", "Neutralization reactions", "Acid-base indicators", "Amphoteric substances", "Polyprotic acids", 
    "Monoprotic acids", "Diprotic acids", "Triprotic acids", "Buffer capacity", "Hydrolysis", "Acid-base equilibrium", 
    "Salts", "Salt hydrolysis", "Strong electrolyte", "Weak electrolyte", "Hydrogen bonding", "Solubility", 
    "Solubility product (Ksp)", "Le Chatelier's principle", "Thermodynamic spontaneity", "Gibbs free energy", 
    "Reaction kinetics", "Activation energy", "Catalysis", "Enzyme catalysis", "Reaction mechanisms", 
    "Electrochemical cells", "Galvanic cells", "Electrolysis", "Faraday's laws of electrolysis", "Nernst equation", 
    "Voltaic cells", "Batteries", "Fuel cells", "Radioactive decay", "Half-life", "Nuclear chemistry", 
    "Radiochemistry", "Organic chemistry", "Alkanes", "Alkenes", "Alkynes", "Aromatic compounds", "Functional groups", 
    "Hydrocarbons", "Isomerism", "Stereochemistry", "Carboxylic acids", "Amines", "Aldehydes", "Ketones", 
    "Alcohols", "Ethers", "Esters", "Polymers", "Organic reactions", "Substitution reactions", "Addition reactions", 
    "Elimination reactions", "Reduction and oxidation in organic chemistry", "Heterocyclic compounds", "Pharmacology", 
    "Pharmaceutical chemistry", "Green chemistry", "Environmental chemistry", "Analytical chemistry", "Chromatography", 
    "Spectroscopy", "Mass spectrometry", "Nuclear magnetic resonance (NMR)", "Infrared spectroscopy (IR)", 
    "Ultraviolet-visible spectroscopy (UV-Vis)", "X-ray diffraction", "Electroanalytical chemistry", "Molecular spectroscopy", 
    "Chemical thermodynamics", "Entropy", "Enthalpy", "Heat of reaction", "Enthalpy of formation", "Bond enthalpies", 
    "Calorimetry", "Heat capacity", "Reversible reactions", "Chemical kinetics", "Rate laws", "Arrhenius equation", 
    "Collision theory", "Activation energy", "Reaction intermediates", "Catalysts", "Phase transitions", "Phase diagrams", 
    "Solubility rules", "Molarity", "Molality", "Normality", "Ideal gas law", "Real gases", "Van der Waals equation", 
    "Gaseous state of matter", "Liquids", "Solids", "Colloids", "Crystallography", "Biochemistry", "Biological molecules", 
    "Amino acids", "Proteins", "Nucleic acids", "Carbohydrates", "Lipids", "Enzyme kinetics", "Metabolism", 
    "Cellular respiration", "Photosynthesis", "ATP synthesis", "Biological buffers", "Metabolic pathways", 
    "Bioorganic chemistry", "Environmental pollution", "Air pollution", "Water pollution", "Soil pollution", 
    "Chemical hazards", "Chemical toxicity", "Radiation chemistry", "Chemistry of materials", "Nanomaterials", 
    "Supramolecular chemistry", "Polymer chemistry", "Surface chemistry", "Colloid chemistry", "Organometallic chemistry", 
    "Photochemistry", "Electrochemistry", "Solvent extraction", "Hydrometallurgy", "Catalysis", "Organic electronics", 
    "Bioengineering", "Chemical engineering", "Material science", "Quantum chemistry", 
    
    # Added Acid and Base Names like Sulfuric Acid
    "Sulfuric acid", "Hydrochloric acid", "Nitric acid", "Acetic acid", "Phosphoric acid", "Citric acid", "Lactic acid", 
    "Formic acid", "Oxalic acid", "Tartaric acid", "Hydrofluoric acid", "Perchloric acid", "Sulfurous acid", 
    "Hydrobromic acid", "Hydroiodic acid", "Carbonic acid", "Boric acid", "Benzoic acid", "Ascorbic acid", 
    "Amino acid", "Acetohydroxamic acid", "Salicylic acid", "Chloric acid", "Muriatic acid", "Gallic acid", 
    "Malic acid", "Succinic acid", "Stearic acid", "Adipic acid", "Butyric acid", "Caproic acid", "Isobutyric acid", 
    "Propionic acid", "Valeric acid", "Acrylic acid", "Formic acid", "Picric acid", "Angelica acid", "Pyruvic acid", 
    "Vinyl acid", "Methylsulfonic acid", "Toluene sulfonic acid", "Fumaric acid", "Maleic acid", "Peracetic acid", 
    "Chlorosulfonic acid", "Dimethyl sulfoxide (DMSO)", "Phthalic acid", "Terephthalic acid", "Isophthalic acid", 
    "Benzene sulfonic acid", "Aliphatic acids", "Alpha-hydroxy acids (AHAs)", "Beta-hydroxy acids (BHAs)", 
    "Trifluoroacetic acid", "Oleic acid", "Linoleic acid", "Stearic acid", "Palmitic acid", "Decanoic acid", 
    "Linolenic acid", "Butyric acid", "Isobutyric acid", "Acylsulfonic acid", "Pyrrole-2-carboxylic acid", "Cinnamic acid", 
    "Phenylacetic acid", "Mandelic acid", "Ethanol acid", "Ethanoic acid", "Butanoic acid", "Dodecanoic acid", 
    "Naphthalene sulfonic acid", "Hydrocinnamic acid", "Methanesulfonic acid", "Capric acid", "Lauric acid", 
    "Stearic acid", "Dodecylbenzenesulfonic acid", "Trichloroacetic acid", "Aminobenzoic acid", "Anthraquinone", 
    "Sodium hydroxide", "Ammonium hydroxide", "Calcium hydroxide", "Magnesium hydroxide", "Lithium hydroxide", 
    "Potassium hydroxide", "Sodium carbonate", "Calcium carbonate", "Potassium carbonate", "Sodium bicarbonate", 
    "Ammonium chloride", "Potassium hydroxide", "Sodium hydroxide", "Calcium hydroxide", "Lithium hydroxide"
    ],
  
    "physics": [
    # **Basic Topics**
    "Motion and forces", "Newton's laws of motion", "Work", "Energy", "Power", "Simple machines", 
    "Electricity", "Magnetism", "Light", "Optics", "Heat", "Temperature", "Atomic physics", "Kinematics", 
    "Dynamics", "Acceleration", "Velocity", "Friction", "Momentum", "Projectile motion", "Circular motion", 
    "Linear motion", "Gravitational force", "Electrostatics", "Magnetic fields", "Electric fields", 
    "Electric current", "Resistance", "Ohm's law", "Capacitors", "Inductance", "Electromagnetic waves", 
    "Reflection of light", "Refraction of light", "Diffraction of light", "Interference of light", 
    "Sound waves", "Wave motion", "Work-energy theorem", "Conservation of energy", "Conservation of momentum", 
    "Thermodynamics basics", "Ideal gas laws", "Pressure and volume", "Internal energy", "Heat transfer", 
    "Specific heat capacity", "Latent heat", "First law of thermodynamics", "Second law of thermodynamics", 
    "Third law of thermodynamics", "Entropy", "Temperature scales", "Specific heat", "Latent heat of fusion", 
    "Latent heat of vaporization", "Simple harmonic motion", "Wave-particle duality", "Buoyancy", "Archimedes' principle", 
    "Electromagnetic spectrum", "Properties of light", "Refraction", "Geometrical optics", "Wave optics", 
    "Photoelectric effect", "Thermal expansion", "Thermocouples", "Work done by a force", "Elastic collisions", 
    "Inelastic collisions", "Conservation of mechanical energy", "Power in electricity", "Electromagnetic induction", 
    "Faraday's law", "Lenz's law", "Magnetic force on a moving charge", "Coulomb's law", "Electric potential", 
    "Capacitance", "Resistors in series and parallel", "Magnetic fields around a current-carrying wire",

    # **Intermediate Topics**
    "Gravitational fields", "Electric potential energy", "Magnetic flux", "Alternating current", "Electromagnetic waves", 
    "Maxwell's equations", "Faraday's law of induction", "Lenz's law", "Electromagnetic radiation", "Wave-particle duality", 
    "Photoelectric effect", "Quantum mechanics", "Schrödinger equation", "Heisenberg uncertainty principle", 
    "Particle-wave duality", "Atomic spectra", "Bohr's model", "Photoelectric effect", "Quantum entanglement", 
    "Quantum tunneling", "Nuclear physics", "Fission and fusion", "Radioactive decay", "Half-life", "Nuclear reactions", 
    "Alpha, beta, gamma radiation", "Magnetic resonance imaging (MRI)", "X-rays", "Semiconductors", "Diodes and transistors", 
    "Magnetism in materials", "Diamagnetism", "Paramagnetism", "Ferromagnetism", "Superconductivity", 
    "Lorentz force", "Energy levels in atoms", "Energy quantization", "Hydrogen atom model", "Electron configuration", 
    "Thermodynamics applications", "Carnot engine", "Heat engines", "Entropy in thermodynamics", "Statistical mechanics", 
    "Thermodynamic cycles", "Thermal equilibrium", "Brownian motion", "Heat conduction", "Conduction and convection", 
    "Radiation heat transfer", "Molecular dynamics", "Kinetic theory of gases", "Ideal gas law", "Boltzmann distribution",
    "Pressure-volume work", "State functions", "Irreversible processes", "Equilibrium thermodynamics", 
    "Classical mechanics", "Conservation of angular momentum", "Newtonian mechanics", "Inertial and non-inertial frames", 
    "Rotational motion", "Moment of inertia", "Angular velocity", "Angular momentum", "Torque", "Torque in rotational dynamics", 
    "Work-energy theorem in rotational motion", "Law of universal gravitation", "Kepler's laws of planetary motion", 
    "Astrophysics basics", "Keplerian motion", "Gravitational potential energy", "Escape velocity",

    # **Advanced Topics**
    "Quantum field theory", "General relativity", "Astrophysics", "Electrodynamics", "Gravitational waves", 
    "Particle accelerators", "String theory", "Supersymmetry", "Quantum chromodynamics", "Quantum electrodynamics", 
    "String theory in physics", "Multiverse theory", "Black holes", "Hawking radiation", "Big bang theory", "Cosmology", 
    "Dark matter", "Dark energy", "Gravitational lensing", "General relativity in cosmology", "Cosmic microwave background", 
    "Einstein's field equations", "Relativistic mechanics", "Special relativity", "Time dilation", "Length contraction", 
    "Lorentz transformations", "Schwarzschild radius", "Geodesics", "Black hole thermodynamics", "Quantum gravity", 
    "M-theory", "String theory dualities", "Superstring theory", "Calabi-Yau manifolds", "Quantum computing and relativity", 
    "Quantum teleportation", "Quantum computing applications", "Superconducting qubits", "Quantum cryptography", 
    "Unification theories", "Higher-dimensional spaces", "Quantum loops", "Tachyons", "Theoretical particle physics", 
    "Lagrangian mechanics", "Hamiltonian mechanics", "Symmetry groups in physics", "Gauge theories", "Yang-Mills theory", 
    "Non-abelian gauge fields", "The Standard Model of particle physics", "Quantum mechanics in curved space", 
    "Gravitational radiation", "Quantum black holes", "Cosmological inflation", "String landscape", "Loop quantum gravity", 
    "Dark matter detection", "Neutrino oscillations", "Exotic matter", "Advanced particle physics", "Collider physics", 
    "Accelerator physics", "High-energy particle collisions", "Relativistic quantum field theory", "Quantum electrodynamics (QED)", 
    "Holographic principle", "AdS/CFT correspondence", "Nuclear astrophysics", "Gravitational wave astronomy", 
    "Cosmological perturbation theory", "Advanced quantum mechanics", "Quantum field theory in curved spacetime", 
    "Quantum cosmology", "High-energy astrophysics", "Neutrino astrophysics", "Quantum liquids", "Quantum Hall effect"
    ],

    "computer_science": [
    # **Basic Topics**
    "Programming fundamentals", "Data structures", "Algorithms", "Loops", "Functions", "Recursion", 
    "Object-oriented programming", "Web development", "Basic HTML", "CSS", "JavaScript", "Front-end development", 
    "Back-end development", "Databases", "SQL", "Relational databases", "Non-relational databases", "Basic Python", 
    "Java basics", "C programming", "C++ programming", "Introduction to algorithms", "Sorting algorithms", 
    "Searching algorithms", "Big O notation", "Array", "Linked list", "Stack", "Queue", "Hash table", "Binary tree", 
    "Graph theory", "Depth-first search", "Breadth-first search", "Graph traversal", "Linked list operations", 
    "Tree operations", "Sorting techniques", "Binary search", "Merge sort", "Quick sort", "Insertion sort", 
    "Heap sort", "Selection sort", "Recursion in programming", "Computer organization", "Assembly language", 
    "Operating system basics", "Processes", "Memory management", "File systems", "I/O operations", "Virtual memory", 
    "Multithreading", "Concurrency", "Introduction to networking", "Internet basics", "IP addressing", "HTTP", "TCP/IP", 
    "Routing and switching", "Basic cybersecurity", "Encryption", "Authentication", "Public key infrastructure (PKI)", 
    "DNS", "Basic cloud computing", "Cloud services (AWS, Azure, GCP)", "Basic machine learning", "Supervised learning", 
    "Unsupervised learning", "Classification", "Regression", "Data visualization", "Data cleaning", "Data wrangling", 
    "Basic statistics", "Descriptive statistics", "Inferential statistics", "Probability theory", "Central limit theorem", 
    "Hypothesis testing", "Linear regression", "Logistic regression", "Decision trees", "Support vector machines", 
    "K-means clustering", "Naive Bayes", "Principal component analysis (PCA)", "Artificial neural networks (ANN)", 
    "Neural network basics", "Gradient descent", "Overfitting", "Underfitting", "Cross-validation", "Hyperparameter tuning", 
    "Natural language processing (NLP)", "Text preprocessing", "Tokenization", "Sentiment analysis", "Text classification", 
    "Bag of words", "TF-IDF", "Latent Dirichlet Allocation (LDA)", "N-grams", "Part of speech tagging", "Named entity recognition (NER)", 

    # **Intermediate Topics**
    "Compilers", "Interpreter", "Lexical analysis", "Syntax analysis", "Code optimization", "Code generation", 
    "Design patterns", "MVC architecture", "Object-oriented design", "UML diagrams", "Database normalization", 
    "Normalization forms (1NF, 2NF, 3NF)", "Indexing in databases", "Transactions", "ACID properties", "Database normalization", 
    "NoSQL databases", "Document-based databases", "Key-value stores", "Graph databases", "Blockchain", "Smart contracts", 
    "Decentralized applications (DApps)", "Consensus algorithms", "Distributed ledger technology", "Cryptocurrency", 
    "Bitcoin", "Ethereum", "Cloud architecture", "Microservices architecture", "Serverless computing", "API design", 
    "RESTful APIs", "GraphQL", "Web security", "Cross-site scripting (XSS)", "SQL injection", "Cross-site request forgery (CSRF)", 
    "OAuth", "JWT (JSON Web Tokens)", "Authorization and authentication", "Public-key cryptography", "RSA encryption", 
    "Diffie-Hellman key exchange", "AES encryption", "Asymmetric encryption", "Symmetric encryption", "TLS/SSL protocols", 
    "Cybersecurity best practices", "Firewalls", "Network security", "Intrusion detection systems", "Denial of Service attacks", 
    "Zero-day attacks", "Penetration testing", "Ethical hacking", "Honeypots", "Distributed denial of service (DDoS)", 
    "Cryptography in networking", "Digital signatures", "Public key cryptography", "Cloud security", "Cloud access security brokers (CASB)", 
    "Cloud-native development", "Containerization (Docker)", "Orchestration (Kubernetes)", "CI/CD pipelines", "DevOps", 
    "Version control (Git)", "GitHub", "GitLab", "Bitbucket", "Unit testing", "Integration testing", "System testing", 
    "Continuous integration", "Continuous delivery", "Testing frameworks", "Test-driven development (TDD)", "Behavior-driven development (BDD)", 
    "Agile development", "Scrum", "Kanban", "Software development life cycle (SDLC)", "Software project management", "Jira", 
    "Kanban board", "Scrum master", "Sprint planning", "Epic stories", "User stories", "Kanban board", "CI/CD pipeline", 
    "Scrum artifacts", "Team collaboration tools", "Cloud-native applications", "Serverless applications", "Function-as-a-Service (FaaS)", 
    "Microservices architecture", "Event-driven architecture", "Pub/Sub model", "Message queues", "Kafka", "RabbitMQ", 
    "Event sourcing", "CQRS (Command Query Responsibility Segregation)", "Container orchestration", "Kubernetes", "Docker", 

    # **Advanced Topics**
    "Artificial intelligence", "Machine learning", "Deep learning", "Reinforcement learning", "Neural networks", 
    "Convolutional neural networks (CNN)", "Recurrent neural networks (RNN)", "Generative adversarial networks (GANs)", 
    "Transfer learning", "AI ethics", "AI fairness", "Explainable AI (XAI)", "AI models", "Deep learning frameworks", 
    "TensorFlow", "PyTorch", "Keras", "Scikit-learn", "Computer vision", "Image processing", "Object detection", 
    "Face recognition", "Optical character recognition (OCR)", "Image segmentation", "Generative models", 
    "Natural language processing (NLP)", "BERT", "GPT-3", "Transformer models", "Attention mechanisms", 
    "Text generation", "Text summarization", "Question answering", "Speech recognition", "Text-to-speech (TTS)", 
    "Speech-to-text (STT)", "Recommender systems", "Collaborative filtering", "Content-based filtering", 
    "Hybrid recommendation systems", "Neural machine translation (NMT)", "Sequence-to-sequence models", 
    "Deep reinforcement learning", "Q-learning", "Monte Carlo Tree Search (MCTS)", "Multi-agent systems", "AI planning", 
    "Fuzzy logic", "Swarm intelligence", "Ant colony optimization", "Genetic algorithms", "Simulated annealing", 
    "Optimization problems", "Graph algorithms", "Big data", "MapReduce", "Hadoop", "Spark", "NoSQL data models", 
    "Distributed databases", "Consistency in distributed systems", "CAP theorem", "Sharding", "Replication", 
    "Data pipelines", "ETL processes", "Data lakes", "Data warehousing", "Data governance", "Business intelligence", 
    "Data mining", "Deep learning for NLP", "Clustering algorithms", "K-means clustering", "DBSCAN", "Hierarchical clustering", 
    "Association rule mining", "Advanced cryptography", "Elliptic curve cryptography", "Homomorphic encryption", 
    "Quantum computing", "Quantum algorithms", "Quantum cryptography", "Quantum machine learning", 
    "Quantum error correction", "Quantum programming languages", "Cloud computing platforms", "AWS", "Google Cloud", 
    "Microsoft Azure", "Kubernetes orchestration", "Serverless computing", "Edge computing", "Fog computing", 
    "Autonomous systems", "Blockchain in IoT", "Decentralized finance (DeFi)", "Distributed ledgers", "Supply chain blockchain",
    "Edge AI", "AI-powered IoT", "Self-driving cars", "Natural language generation (NLG)", "Federated learning", "AI in healthcare",
    "AI in finance", "AI in cybersecurity", "AI in robotics", "AI in business", "Explainable AI (XAI)"
    ],

    "AI_ML": [
    # **Basic Topics**
    "Machine learning", "Supervised learning", "Unsupervised learning", "Semi-supervised learning", 
    "Reinforcement learning", "Deep learning", "Neural networks", "Classification algorithms", "Regression models", 
    "Decision trees", "Linear regression", "Logistic regression", "K-nearest neighbors (KNN)", "Support vector machines (SVM)", 
    "Naive Bayes", "K-means clustering", "Hierarchical clustering", "Dimensionality reduction", "Principal component analysis (PCA)", 
    "Feature engineering", "Feature scaling", "Cross-validation", "Training and testing sets", "Overfitting", "Underfitting", 
    "Bias-variance tradeoff", "Gradient descent", "Stochastic gradient descent", "Loss functions", "Cost function", "Model evaluation", 
    "Confusion matrix", "Precision", "Recall", "F1-score", "ROC curve", "AUC (Area under curve)", "Accuracy", 
    "Hyperparameter tuning", "Grid search", "Random search", "Data preprocessing", "Data cleaning", "Data normalization", 
    "Data augmentation", "Transfer learning", "Artificial intelligence", "Artificial neural networks (ANN)", "Backpropagation", 
    "Deep learning basics", "Activation functions", "ReLU", "Sigmoid", "Tanh", "Softmax", "RNN (Recurrent Neural Networks)", 
    "LSTM (Long Short-Term Memory)", "GRU (Gated Recurrent Unit)", "Convolutional neural networks (CNN)", "Pooling layers", 
    "Convolution layers", "Fully connected layers", "Dropout", "Batch normalization", "Data pipelines", "Feature selection", 
    "Autoencoders", "Generative adversarial networks (GANs)", "Unsupervised learning algorithms", "Clustering", "Dimensionality reduction", 
    "Tensors", "TensorFlow", "Keras", "PyTorch", "Scikit-learn", "Jupyter notebooks", "Hyperparameter tuning", "Model training", 
    "Ensemble learning", "Random Forest", "Boosting", "Bagging", "XGBoost", "AdaBoost", "LightGBM", "CatBoost", "Stacking", 
    "Model deployment", "Model serialization", "AI ethics", "Ethical AI", "Bias in AI", "Fairness in AI", "Transparency in AI", 
    "Explainable AI (XAI)", "AI regulations", "AI policy", "AI governance", "Responsible AI", "Reproducibility in ML", 
    "Reinforcement learning", "Markov decision process (MDP)", "Q-learning", "Policy gradient methods", "Deep Q Networks (DQN)", 
    "Monte Carlo methods", "Temporal difference learning", "Exploration vs exploitation", "POMDP (Partially Observable MDP)", 
    "Multi-agent systems", "AI in robotics", "AI in gaming", "AI in healthcare", "AI in finance", "AI in marketing", "AI in business", 
    "AI in autonomous systems", "Smart cities", "Chatbots", "Natural language processing (NLP)", "Text classification", "Text summarization", 
    "Sentiment analysis", "Named entity recognition (NER)", "Machine translation", "Speech recognition", "Speech-to-text", 
    "Text-to-speech", "Reinforcement learning in NLP", "Word embeddings", "Word2Vec", "GloVe", "FastText", "Transformers", 
    "Attention mechanism", "BERT (Bidirectional Encoder Representations from Transformers)", "GPT (Generative Pre-trained Transformer)", 
    "XLNet", "T5", "RoBERTa", "Turing-NLG", "Natural language generation (NLG)", "Machine reading comprehension", 
    "Text generation", "Question answering", "Summarization", "Paraphrase generation", "Dialog systems", "Chatbots", "Conversational AI", 
    "Speech-to-text", "Audio signal processing", "Voice assistants", "Multimodal learning", "Text-to-speech", "Emotion detection", 
    "Intent recognition", "Entity extraction", "Topic modeling", "Latent Dirichlet Allocation (LDA)", "TF-IDF", "Bag-of-words", 
    "Topic modeling", "N-grams", "NLP pipelines", "Text preprocessing", "Tokenization", "Stemming", "Lemmatization", 
    "Stopwords removal", "Spacy", "NLTK", "TextBlob", "FastText", "HuggingFace", "Word embeddings", "ELMo", "GloVe", "Word2Vec", 

    # **Intermediate Topics**
    "Deep reinforcement learning", "Deep Q networks (DQN)", "Policy gradient methods", "Actor-Critic", "Double DQN", 
    "A3C (Asynchronous Advantage Actor-Critic)", "TRPO (Trust Region Policy Optimization)", "PPO (Proximal Policy Optimization)", 
    "Curiosity-driven learning", "Imitation learning", "Model-free reinforcement learning", "Model-based reinforcement learning", 
    "Reinforcement learning in robotics", "Multi-agent reinforcement learning", "Sim-to-real transfer", "Exploration strategies", 
    "Reward shaping", "Multi-armed bandit problem", "Deep convolutional neural networks (DCNN)", "U-Net architecture", 
    "Residual networks (ResNet)", "DenseNet", "Inception networks", "VGGNet", "MobileNet", "EfficientNet", "Capsule networks", 
    "Recurrent Neural Networks (RNN)", "Long Short-Term Memory (LSTM)", "Attention mechanism", "Sequence-to-sequence models", 
    "Bidirectional LSTMs", "Transformers", "GPT (Generative Pre-trained Transformer)", "BERT (Bidirectional Encoder Representations from Transformers)", 
    "GPT-3", "T5", "BART", "ALBERT", "XLNet", "XLNet for NLP", "GPT-2", "Transformer architecture", "Self-attention mechanism", 
    "Reinforcement learning for NLP", "Policy gradient methods", "Proximal Policy Optimization (PPO)", "Actor-Critic methods", 
    "Deep Reinforcement Learning (DRL)", "Transfer learning in NLP", "Fine-tuning BERT", "Pre-training models", "Masking in BERT", 
    "Transfer learning for image classification", "Fine-tuning CNNs", "Style transfer", "Transfer learning for text classification", 
    "Multimodal AI", "Generative models", "Generative Adversarial Networks (GAN)", "Conditional GAN", "CycleGAN", "WGAN", 
    "DCGAN", "VAE (Variational Autoencoders)", "Deep Convolutional GANs", "StyleGAN", "Fid score", "Perceptual loss", 
    "Supervised vs unsupervised learning", "Semi-supervised learning", "Active learning", "Self-supervised learning", 
    "Few-shot learning", "Zero-shot learning", "Neural Architecture Search (NAS)", "AutoML", "Bayesian optimization", 
    "Hyperparameter optimization", "Model evaluation metrics", "Precision", "Recall", "F1-score", "AUC-ROC", "Precision-Recall curve", 
    "Cross-validation", "K-fold cross-validation", "Bootstrap sampling", "Leave-one-out cross-validation", "Hyperparameter tuning", 
    "Hyperparameter grid search", "Random search", "Bayesian optimization for hyperparameter tuning", "Model complexity", 
    "Feature engineering", "Feature selection", "Model interpretability", "Explainable AI (XAI)", "SHAP values", "LIME", 
    "Partial dependence plots", "Global and local interpretability", "Fairness in AI", "Bias in AI", "AI accountability", 
    "Responsible AI", "AI governance", "AI transparency", "Federated learning", "Decentralized learning", "Privacy-preserving AI", 
    "Homomorphic encryption", "Differential privacy", "AI in edge computing", "AI in robotics", "Edge AI", "AI in IoT", 
    "AI in healthcare", "AI in finance", "AI in education", "AI in autonomous systems", "AI for climate change", "AI in agriculture", 
    "AI in creative arts", "AI in business", "AI in marketing", "AI in manufacturing", "AI in transportation", "AI in supply chain", 
    "AI for social good", "AI-powered chatbots", "AI in content generation", "AI in visual recognition", "AI in diagnostics", 
    "AI in drug discovery", "AI for mental health", "AI for security", "AI-powered analytics", "AI-based recommender systems"
    ],
  
    "deep_learning": [
    # **Basic Topics**
    "Neural networks", "Perceptron", "Feedforward neural networks", "Single-layer perceptron", "Multi-layer perceptron", 
    "Backpropagation", "Gradient descent", "Stochastic gradient descent", "Loss functions", "Mean squared error", "Cross-entropy loss", 
    "Activation functions", "Sigmoid", "Tanh", "ReLU (Rectified Linear Unit)", "Leaky ReLU", "Softmax", "ELU (Exponential Linear Unit)", 
    "Batch normalization", "Dropout", "Gradient clipping", "Weight initialization", "Optimizers", "SGD (Stochastic Gradient Descent)", 
    "Adam optimizer", "RMSprop", "Adagrad", "Momentum", "Nesterov Accelerated Gradient", "Learning rate schedules", "Learning rate decay", 
    "Mini-batch gradient descent", "Epochs", "Iterations", "Overfitting", "Underfitting", "Early stopping", "Hyperparameter tuning", 
    "Model evaluation", "Accuracy", "Precision", "Recall", "F1-score", "Confusion matrix", "ROC curve", "AUC", "Cross-validation", 
    "Data augmentation", "Data preprocessing", "Feature scaling", "Feature engineering", "Text preprocessing", "Normalization", 
    "Regularization", "L1 regularization", "L2 regularization", "Elastic net", "Keras", "TensorFlow", "PyTorch", "Theano", 
    "Caffe", "MXNet", "Scikit-learn", "Jupyter notebooks", "Model training", "Model testing", "Model inference", "Model serialization", 
    "Transfer learning", "Pre-trained models", "Fine-tuning", "Model distillation", "Model quantization", "Knowledge transfer", 
    "Hyperparameter optimization", "Grid search", "Random search", "Bayesian optimization", "AutoML", "TensorFlow Lite", "ONNX (Open Neural Network Exchange)", 
    "Model deployment", "Cloud-based deployment", "Edge deployment", "Deployment on mobile", "Model serving", "TensorFlow Serving", 
    "FastAPI for model serving", "Docker for deployment", "Model versioning", "TensorFlow Hub", "HuggingFace", "Model interpretability", 
    "Explainable AI (XAI)", "SHAP values", "LIME", "Saliency maps", "Integrated Gradients", "Activation maps", "Class activation maps (CAM)", 
    "Grad-CAM", "Feature visualization", "Neural network visualization", "Model debugging", "Error analysis", "Bias-variance tradeoff", 

    # **Intermediate Topics**
    "Convolutional neural networks (CNN)", "Convolutional layers", "Pooling layers", "Max pooling", "Average pooling", "Fully connected layers", 
    "Filters", "Kernels", "Stride", "Padding", "CNN architectures", "LeNet", "AlexNet", "VGGNet", "ResNet", "InceptionNet", "DenseNet", 
    "MobileNet", "EfficientNet", "Capsule networks", "U-Net", "Generative Adversarial Networks (GAN)", "Conditional GAN", "DCGAN (Deep Convolutional GAN)", 
    "WGAN (Wasserstein GAN)", "CycleGAN", "Pix2Pix", "VAE (Variational Autoencoders)", "Self-supervised learning", "Contrastive learning", 
    "SimCLR", "MoCo", "BYOL", "Deep Q Networks (DQN)", "Actor-Critic methods", "Proximal Policy Optimization (PPO)", "Reinforcement learning", 
    "Markov decision process (MDP)", "Q-learning", "Policy gradients", "Exploration vs exploitation", "Model-free vs model-based RL", "Deep reinforcement learning", 
    "Experience replay", "Monte Carlo methods", "Temporal difference learning", "Reward shaping", "Policy gradient algorithms", "A3C (Asynchronous Advantage Actor-Critic)", 
    "Dueling DQN", "Attention mechanism", "Transformer architecture", "Multi-head attention", "Self-attention", "Positional encoding", "BERT (Bidirectional Encoder Representations from Transformers)", 
    "GPT (Generative Pre-trained Transformer)", "XLNet", "T5 (Text-to-Text Transfer Transformer)", "RoBERTa", "BART", "Transformers in NLP", "Encoder-decoder architecture", 
    "Attention is all you need", "Pre-trained transformer models", "Attention-based models for computer vision", "Vision transformers (ViT)", "Image transformers", 
    "Multi-modal learning", "Cross-modal learning", "Siamese networks", "Triplet networks", "Neural architecture search", "AutoML", "Differentiable architecture search", 
    "Graph neural networks (GNN)", "Message passing neural networks", "Graph convolutions", "Graph embeddings", "Node classification", "Link prediction", 
    "Graph attention networks (GAT)", "Knowledge graphs", "Graph-based learning", "Sequence-to-sequence models", "Encoder-decoder networks", "Attention-based models", 
    "Bidirectional LSTM", "Transformers for sequential data", "LSTM for sequence learning", "GRU (Gated Recurrent Unit)", "RNN for sequential data", "Vanishing gradient problem", 
    "Long-range dependencies", "Temporal convolutions", "Time series forecasting with deep learning", "Anomaly detection", "Autoregressive models", "Multivariate time series forecasting", 

    # **Advanced Topics**
    "Deep convolutional generative models", "BigGAN", "StyleGAN", "StyleGAN2", "BigBERT", "Cross-lingual pretraining", "Masked language models", "Pre-training and fine-tuning transformers", 
    "Large-scale pre-trained models", "Zero-shot learning", "Few-shot learning", "Meta-learning", "Model-based meta-learning", "Model-agnostic meta-learning", "Meta-reinforcement learning", 
    "Active learning", "Uncertainty in deep learning", "Bayesian deep learning", "Monte Carlo dropout", "Bayesian networks", "Uncertainty quantification in deep learning", 
    "Neural architecture search", "Evolutionary algorithms for NAS", "Reinforcement learning-based NAS", "Neuroevolution", "Differentiable neural architecture search", 
    "Efficient neural architectures", "MobileNetV2", "EfficientNetV2", "Sparse neural networks", "Pruning", "Quantization", "Low-precision networks", "Hardware-efficient deep learning", 
    "Energy-efficient neural networks", "Edge AI", "Neural networks on mobile", "Neuromorphic computing", "Quantum machine learning", "Quantum neural networks", 
    "Deep learning for healthcare", "Deep learning for drug discovery", "AI for genomics", "Deep learning for precision medicine", "AI for radiology", "AI for pathology", 
    "Deep learning in robotics", "Robotic control with deep learning", "AI in autonomous vehicles", "Deep learning in gaming", "AI for creative industries", 
    "Deep learning in finance", "Financial time series forecasting", "AI in business intelligence", "Deep learning in cybersecurity", "AI for anomaly detection", 
    "Transfer learning for speech recognition", "Transfer learning for visual recognition", "Deep learning for reinforcement learning", "AI for ethical decision making", 
    "Bias in deep learning models", "Explainable deep learning", "Interpretability of deep models", "Fairness in deep learning", "Adversarial attacks", "Adversarial robustness", 
    "Robust optimization in deep learning", "Deep learning for climate modeling", "Deep learning for environmental protection", "Deep learning in personalized education", 
    "Ethical considerations in deep learning", "AI in public policy", "AI for social good", "AI in space exploration", "AI in autonomous systems"
    ],

    "coding": [
    # **Basic Topics**
    "Programming languages", "Syntax", "Semantics", "Variables", "Constants", "Data types", "Primitive data types", "Compound data types", 
    "Control structures", "If-else statements", "Switch-case", "Loops", "For loop", "While loop", "Do-while loop", "Break and continue", 
    "Functions", "Function arguments", "Function return values", "Recursion", "Scope of variables", "Global vs local variables", 
    "Error handling", "Exception handling", "Debugging", "Print statements", "Debugger tools", "Unit testing", "Test-driven development (TDD)", 
    "Assertions", "Input and output (I/O)", "File handling", "Reading from files", "Writing to files", "Command-line arguments", 
    "Arrays", "Lists", "Strings", "String manipulation", "String slicing", "String formatting", "Array operations", "Array indexing", 
    "String matching algorithms", "Searching algorithms", "Sorting algorithms", "Linked lists", "Stacks", "Queues", "Dictionaries", 
    "Sets", "Tuples", "Lists vs arrays", "Dynamic arrays", "Array resizing", "Matrix operations", "Bit manipulation", 
    "Memory management", "Garbage collection", "Recursion vs iteration", "Algorithmic complexity", "Big-O notation", "Space complexity", 
    "Time complexity", "Optimization techniques", "Complexity analysis", "Object-Oriented Programming (OOP)", "Classes", "Objects", "Inheritance", 
    "Polymorphism", "Encapsulation", "Abstraction", "Constructors", "Destructors", "Static methods", "Instance methods", "Class variables", 
    "Encapsulation", "Interfaces", "Abstract classes", "Design patterns", "Singleton pattern", "Factory pattern", "Observer pattern", "Strategy pattern", 
    "Decorator pattern", "Model-View-Controller (MVC)", "State pattern", "Command pattern", "Adapter pattern", "Composite pattern", "Proxy pattern", 
    "Dependency injection", "Solid principles", "DRY principle", "YAGNI principle", "KISS principle", "Coding standards", "Code readability", 
    "Refactoring", "Code review", "Version control", "Git", "GitHub", "GitLab", "SVN", "Mercurial", "Branching", "Merging", "Commit messages", 
    "Continuous integration (CI)", "Continuous delivery (CD)", "Docker", "Containerization", "Virtual machines", "CI/CD pipelines", 
    "Automated testing", "Test coverage", "Test cases", "Mocking", "Stubs", "Integration testing", "Unit testing frameworks", "Jest", "JUnit", 
    "JUnit tests", "Mocha", "PyTest", "RSpec", "Code profiling", "Performance optimization", "Memory leaks", "Code complexity analysis", 
    "Error logging", "Error handling patterns", "Exception classes", "Return codes", "Logging libraries", "Event-driven programming", 
    "Asynchronous programming", "Callbacks", "Promises", "Async/await", "Concurrency", "Threads", "Thread synchronization", "Thread safety", 
    "Deadlocks", "Mutexes", "Semaphores", "Race conditions", "Multithreading", "Parallel programming", "MapReduce", "Shared memory", 
    "Distributed computing", "MapReduce algorithms", "Synchronization techniques", "Resource allocation", "Task scheduling", "Event loops", 
    "Signal handling", "Message passing", "Inter-process communication (IPC)", "Low-level programming", "Assembly language", "C", "C++", 
    "Memory addresses", "Pointers", "Memory allocation", "Manual memory management", "Segmentation faults", "Stack and heap", "Pointer arithmetic", 
    "Bitwise operations", "Assembly programming", "Machine code", "CPU architecture", "Compilers", "Linkers", "Loaders", "Memory-mapped I/O", 
    "Basic Operating System concepts", "Interrupts", "Context switching", "System calls", "Process management", "Multi-tasking", "Virtual memory", 
    "Hardware abstraction", "System-level programming", "Kernel programming", "Embedded systems", "Firmware development", 

    # **Advanced Topics**
    "Functional programming", "First-class functions", "Higher-order functions", "Pure functions", "Immutability", "Lazy evaluation", 
    "Monads", "Lambdas", "Map, reduce, and filter", "Currying", "Partial application", "Algebraic data types", "Pattern matching", 
    "Tail recursion", "Recursion optimization", "Functional programming languages", "Haskell", "Scala", "Parallel computing", "GPU programming", "CUDA", "Parallel algorithms", "Distributed computing systems", "MapReduce", "Distributed file systems", 
    "Distributed databases", "CAP theorem", "Event sourcing", "Message queues", "Event-driven architecture", "Microservices architecture", 
    "Service-oriented architecture (SOA)", "RESTful APIs", "GraphQL", "WebSockets", "Asynchronous I/O", "Serverless computing", 
    "Message brokers", "Kafka", "RabbitMQ", "Advanced Database programming", "SQL optimization", "Indexing", "Query optimization", 
    "Database normalization", "Transactions", "ACID properties", "CAP theorem in databases", "NoSQL databases", "Document-based databases", 
    "Key-value stores", "Graph databases", "Database sharding", "Big data programming", "Data pipelines", "ETL processes", "Spark", 
    "Hadoop", "Flink", "Distributed caching", "Redis", "Memcached", "Event-driven programming in microservices", "APIs in microservices", 
    "Web frameworks", "Django", "Flask", "Ruby on Rails", "Spring Boot", "Express.js", "Vue.js", "Angular", "React", "Node.js", "PHP", 
    "REST API development", "API versioning", "OAuth", "JWT", "API authentication", "GraphQL APIs", "WebSockets", "Socket.io", 
    "API documentation", "OpenAPI", "Swagger", "Postman", "Web services", "SOAP", "RPC", "Mobile app development", "Native app development", 
    "React Native", "Flutter", "Xamarin", "Mobile UI/UX design", "Mobile app testing", "Mobile app debugging", "Cross-platform development", 
    "State management in mobile apps", "Redux", "Context API", "Mobile app security", "Data persistence in mobile apps", "Push notifications", 
    "App distribution", "App store optimization", "App deployment", "Hybrid mobile apps", "Mobile app architecture", "MVVM", "MVP", "MVC", 
    "App performance optimization", "Mobile database integration", "Offline storage", "Push notifications", "Location-based services"
],
 
    "programming_languages": [
    # **Python**
    "Syntax", "Data types", "Variables", "Operators", "Control flow (if-else, loops)", "Functions", "OOP in Python", 
    "List comprehensions", "Error handling", "Lambda functions", "Decorators", "Generators", "Modules and packages", "File handling", 
    "Context managers", "Virtual environments", "Unit testing", "Django", "Flask", "Machine learning with Python (scikit-learn, TensorFlow, Keras)", 
    "Data science libraries (NumPy, pandas, Matplotlib)", "Multithreading and multiprocessing", "Asyncio", "Python memory management", 
    "Memory leak detection", "Python C extensions", "Python performance optimization", "Regular expressions in Python", "Concurrency with asyncio", 
    "Python packaging", "Python packaging tools (setuptools, pip)", "Unit testing with pytest", "Data visualization", "Web scraping", 
    "API development with Flask/FastAPI", "Database integration with SQLAlchemy", "Python for automation", "Python for networking", "Python for system administration", 
    "Python for GUI (Tkinter, PyQt)", "Python performance profiling", "Python for data engineering", "Machine Learning deployment", "FastAPI with Python", "Async programming with Python"

    # **Java**
    "Java syntax", "Data types", "Control flow", "Arrays", "Collections framework (List, Set, Map)", "Object-Oriented Programming (OOP) in Java", 
    "Interfaces and Abstract classes", "Java streams", "Lambda expressions", "Multithreading in Java", "JVM and JRE", "Garbage collection", 
    "Exception handling", "Java I/O", "Serialization and deserialization", "JDBC for database interaction", "JavaFX for GUI", "Spring framework", 
    "Spring Boot", "Java EE", "JPA (Java Persistence API)", "Java for Android", "JUnit for unit testing", "Unit testing with Mockito", "JVM performance tuning", 
    "Design patterns in Java", "Concurrency and synchronization", "Reflection in Java", "Java annotations", "Java security", "Java networking", 
    "Java virtual machine internals", "JVM optimization", "Advanced Garbage Collection techniques", "Java profiling and monitoring", "Java microservices", 
    "Java 9 modules", "Reactive programming with Java", "JavaFX", "Java for cloud-native applications", "Java with Kubernetes", "Java RESTful services", "Spring Cloud", "Java microservices with Spring Boot"

    # **C++**
    "C++ syntax", "Data types", "Pointers", "Dynamic memory allocation", "Control flow", "Object-Oriented Programming (OOP) in C++", "Classes and Objects", 
    "Inheritance", "Polymorphism", "Encapsulation", "Abstraction", "C++ templates", "STL (Standard Template Library)", "Containers (vector, map, list, etc.)", 
    "Algorithms in C++ (sorting, searching)", "Exception handling", "Function overloading", "Operator overloading", "Multiple inheritance", "Memory management in C++", 
    "C++ for game development", "C++ for embedded systems", "Multi-threading in C++", "C++ with OpenGL", "C++ for GUI development (Qt, GTK)", 
    "C++ profiling and optimization", "C++ memory management (RAII)", "C++ smart pointers", "C++ performance optimization", "C++ networking", "C++ for real-time systems", 
    "C++ libraries for AI and ML (TensorFlow, Dlib)", "C++ performance analysis tools", "C++ for concurrent systems", "C++ with CUDA", "C++ for high-performance computing"

    # **JavaScript**
    "JavaScript syntax", "Data types", "Control flow", "Functions", "Closures", "Callbacks", "Promises", "Async/await", "JavaScript objects", 
    "DOM manipulation", "Event handling", "ES6 features (let, const, arrow functions, destructuring)", "Promises and async programming", "ES6+ JavaScript", 
    "JavaScript frameworks (React, Vue, Angular)", "JavaScript for backend (Node.js)", "NPM (Node Package Manager)", "JavaScript testing (Mocha, Jest)", 
    "JavaScript and APIs (RESTful, GraphQL)", "JavaScript for web scraping (Puppeteer)", "Web performance optimization", "Web security", "JavaScript design patterns", 
    "Functional programming in JavaScript", "JavaScript for mobile apps (React Native)", "TypeScript", "JavaScript profiling", "JavaScript memory management", 
    "Event loop and concurrency model", "Service workers", "Web components", "WebSockets", "JavaScript performance tuning", "Building PWAs (Progressive Web Apps)"

    # **Ruby**
    "Ruby syntax", "Data types", "Control structures", "OOP in Ruby", "Ruby gems", "Ruby on Rails", "ActiveRecord", "Ruby block, Proc, and lambda", 
    "Ruby for web development", "Ruby testing with RSpec", "Ruby for automation", "Ruby for API development", "Ruby metaprogramming", "Exception handling in Ruby", 
    "Ruby collections (arrays, hashes, sets)", "Regular expressions in Ruby", "Ruby for DevOps", "Ruby for system administration", "Concurrency in Ruby", 
    "Ruby for desktop applications", "Ruby on Rails for MVC architecture", "Ruby for building APIs", "Ruby for scripting", "Ruby performance optimization", "Ruby for cloud"

    # **Swift**
    "Swift syntax", "Control structures", "Optionals", "Swift collections (Array, Dictionary, Set)", "Functions and closures", "OOP in Swift", 
    "Swift for iOS development", "Xcode IDE", "SwiftUI", "iOS UI components", "Memory management in Swift (ARC)", "Swift performance optimization", 
    "Concurrency in Swift", "Protocol-oriented programming", "Unit testing in Swift", "Swift for machine learning", "Swift for server-side programming (Vapor)", 
    "Swift and Core Data", "Swift with Firebase", "Swift for mobile game development", "SwiftUI vs UIKit", "Swift with ARKit", "Swift data bindings", 
    "Swift for networking", "Swift design patterns", "Swift for animations", "Swift for cryptography", "Swift for data persistence", "Swift for VR/AR"

    # **Go**
    "Go syntax", "Go functions", "Go control structures", "Go slices and arrays", "Go goroutines", "Go channels", "Concurrency in Go", "Go struct and interfaces", 
    "Go for backend development", "Go testing with GoTest", "Go memory management", "Go packages", "Go for web development (Gin, Echo)", 
    "Go with Docker", "Go microservices", "Go profiling and optimization", "Go for cloud computing", "Go in DevOps", "Go for networking", "Go for distributed systems", 
    "Go for API development", "Go and RESTful services", "Go error handling", "Go performance tuning", "Go for big data", "Go for event-driven systems"

    # **Rust**
    "Rust syntax", "Ownership and borrowing", "Rust memory model", "Rust traits", "Rust concurrency", "Rust with WebAssembly", "Rust for systems programming", 
    "Rust for web development (Rocket, Actix)", "Rust error handling", "Rust and async programming", "Rust with databases", "Rust for embedded systems", 
    "Rust for game development", "Rust for networking", "Rust for CLI tools", "Rust for performance optimization", "Rust data structures", "Rust and FFI", 
    "Rust with cryptography", "Rust for blockchain development", "Rust unit testing", "Rust for machine learning", "Rust performance profiling"

    # **PHP**
    "PHP syntax", "PHP functions", "PHP arrays", "PHP OOP", "PHP error handling", "PHP for web development (Laravel, Symfony)", "PHP for backend", "PHP for CMS", 
    "PHP for database interaction (MySQL, PostgreSQL)", "PHP for APIs", "PHP for RESTful services", "PHP security", "PHP session handling", 
    "PHP cookies", "PHP with AJAX", "PHP frameworks (Laravel, Symfony, Zend)", "PHP for command-line scripts", "PHP unit testing", "PHP performance optimization", 
    "PHP debugging", "PHP and caching", "PHP for microservices", "PHP for cloud", "PHP with Redis"

    # **Kotlin**
    "Kotlin syntax", "Kotlin OOP", "Kotlin functions", "Kotlin collections", "Kotlin for Android development", "Kotlin null safety", "Kotlin extension functions", 
    "Kotlin coroutines", "Kotlin for web development (Ktor)", "Kotlin unit testing", "Kotlin with Firebase", "Kotlin for backend", "Kotlin memory management", 
    "Kotlin for mobile game development", "Kotlin for multiplatform programming", "Kotlin with Spring Boot", "Kotlin for data science", "Kotlin for server-side applications"

    # **HTML, CSS, SQL**
    "html","css","sql","HTML syntax", "HTML5 tags", "Forms and inputs", "Semantic HTML", "CSS syntax", "CSS selectors", "CSS box model", "Flexbox", "CSS Grid", "CSS transitions", 
    "CSS animations", "CSS variables", "Responsive web design", "CSS media queries", "CSS frameworks (Bootstrap, Tailwind)", "HTML5 APIs", "HTML forms", 
    "SQL queries", "SQL joins", "SQL subqueries", "SQL aggregate functions", "SQL indexing", "SQL normalization", "SQL optimization", "Database design", 
    "SQL transaction management", "SQL security", "SQL for analytics", "NoSQL databases", "MongoDB", "Redis", "Cassandra", "Elasticsearch", "GraphQL", 
    "SQL performance tuning", "SQL for data warehousing", "SQL with Hadoop", "SQL for big data analytics"

    # **NoSQL**
    "NoSQL basics", "Key-value stores", "Document-based databases", "Graph databases", "Column-family stores", "MongoDB", "Cassandra", "Firebase", "Elasticsearch"

    # **.NET (C#)**
    "C# syntax", "Data types", "Variables", "Operators", "Control structures", "Functions", "Methods", "Exception handling", "OOP in C#", 
    "Inheritance", "Polymorphism", "Encapsulation", "Abstract classes", "Interfaces", "Delegates", "Events", "LINQ (Language Integrated Query)", 
    "Lambda expressions", "Collections in C# (List, Dictionary, Queue)", "Generics in C#", "Namespaces", "Assemblies", "Namespaces", 
    "Reflection in C#", "Dynamic types in C#", "Events and delegates", "C# memory management", "Garbage collection in .NET", "Threading and concurrency", 
    "Async programming in C#", "Task Parallel Library (TPL)", "Entity Framework", "ASP.NET (Web Forms, MVC, Web API, Blazor)", 
    "ASP.NET Core", "Razor pages", "Dependency Injection in .NET", "Unit testing in .NET (xUnit, NUnit, MSTest)", "Unit testing with Moq", "C# for web development", 
    "C# for desktop applications (WinForms, WPF)", "C# for mobile development (Xamarin)", "C# for cloud development (Azure)", "C# for game development (Unity)", 
    "C# design patterns", "Model-View-Controller (MVC) in ASP.NET", "Model-View-ViewModel (MVVM) in WPF", "C# for microservices", "Web API development in .NET", 
    "C# performance tuning", "C# security", "SignalR for real-time communication", "Authentication and Authorization in ASP.NET Core", 
    "Routing in ASP.NET Core", "Middleware in ASP.NET Core", "C# for RESTful services", "C# with SQL Server and NoSQL", "C# for distributed systems", 
    "C# for cloud services (Azure Functions, Azure App Services)", "LINQ to SQL", "Azure SDK for .NET", "Blazor (WebAssembly and Server)", "C# for Web APIs",
    "Entity Framework Core", "Unit testing with NUnit", "Asynchronous programming patterns", "Design patterns in .NET", "Reflection in .NET", 
    "Cross-platform .NET Core", "C# for Linux and macOS development", "C# with Docker", "C# with Kubernetes", "C# for DevOps"
]

}
